### ISSUE TITLE
ADAP cannot open a tab

### ISSUE THREAD

**Issue by gabijennings** [ADAP-BIG/adap-big.github.io#1]
Hey I am using ADAP-BIG for the first time and I am trying to upload my file for the LCMS workflow but I keep getting the error message that "ADAP cannot open a tab" I am not sure how to fix this. Please help
<img width="1440" alt="Screen Shot 2022-09-29 at 10 05 47 AM" src="https://user-images.githubusercontent.com/114674980/193053642-6f00bddb-0ff5-4380-8ed1-8474c4c96e63.png">

**Comment by asmirn1** [comment]
@gabijennings 

It looks like you are trying to open the tap with the results of Chromatogram Builder, but that step wasn't executed yet.

You have several options execute it:

### Option 1 
When creating a project, make sure that the option Execute Entire Workflow is selected:
<img width="1268" alt="Screen Shot 2022-09-29 at 10 24 09 AM" src="https://user-images.githubusercontent.com/13631120/193057989-10e69a00-181f-4f1e-810d-4710608feb5c.png">

### Option 2 
If the project has already been created, you can execute the entire workflow from the menu Run -> Run Entire Workflow, or by clicking the third green button in the toolbar:
<img width="278" alt="Screen Shot 2022-09-29 at 10 30 14 AM" src="https://user-images.githubusercontent.com/13631120/193059527-dd73c180-9667-4d32-adf8-692b1d9acde5.png">

### Option 3 
If you don't want to execute the entire workflow, you need to execute each step manually. For example, to execute the Chromatogram Builder step, you need to click the second button in the workflow bar:
<img width="288" alt="Screen Shot 2022-09-29 at 10 26 03 AM" src="https://user-images.githubusercontent.com/13631120/193058557-cea371b1-1bd1-47b6-8861-2d8536b224a4.png">
Then, you'll see the same message as in your question. But after that, you can select execute this step either from the menu (Run -> Run Workflow Step on Single Sample or Run -> Run Workflow Step on All Samples)  or the toolbar:
<img width="274" alt="Screen Shot 2022-09-29 at 10 32 34 AM" src="https://user-images.githubusercontent.com/13631120/193060095-199c3953-93a8-4bd7-947b-579e286c5da7.png">

**Comment by gabijennings** [comment]
Thank you for responding to quickly! I ensured that the "execute entire workflow" box was checked and I tried to run the entire workflow but now I am getting an "Invocation Target Exception"
<img width="1208" alt="Screen Shot 2022-09-29 at 10 41 18 AM" src="https://user-images.githubusercontent.com/114674980/193062622-0ed97fd3-9b48-44a2-b2bf-286106965266.png">

**Comment by asmirn1** [comment]
@gabijennings Could you copy text from the log window (bottom-right) and paste it here? Please copy the last 20-30 lines or as many as you can.

**Comment by gabijennings** [comment]
I couldn't paste the last few lines but this is what I could get


Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76) ~[adap-big-app.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273) ~[adap-big-app.jar:?]
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83) ~[adap-big-app.jar:?]
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1859) ~[adap-big-app.jar:?]
	... 48 more
Caused by: java.lang.NullPointerException: Cannot read the array length because "<local6>" is null
	at org.dulab.adapbig.workflow.ArgumentList.fillArguments(ArgumentList.java:74) ~[adap-big-app.jar:?]
	at org.dulab.adapbig.workflow.Workflow.executeModule(Workflow.java:187) ~[adap-big-app.jar:?]
	at org.dulab.adapbig.workflow.Workflow.executeWorkflow(Workflow.java:113) ~[adap-big-app.jar:?]
	at org.dulab.adapbig.adapbigapp.MainController.runEntireWorkflow(MainController.java:476) ~[adap-big-app.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76) ~[adap-big-app.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273) ~[adap-big-app.jar:?]
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83) ~[adap-big-app.jar:?]
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1859) ~[adap-big-app.jar:?]
	... 48 more

**Comment by asmirn1** [comment]
@gabijennings Thank you!

For some reason, ADAP-BIG couldn't read the raw data files that you selected. I'm not quite sure why. Could you make a screenshot of the filled-out "New Project" window when you are creating a project?

**Comment by gabijennings** [comment]
<img width="768" alt="Screen Shot 2022-09-29 at 1 54 11 PM" src="https://user-images.githubusercontent.com/114674980/193106425-a24d178a-c483-471b-88b8-c2b167991e7e.png">

**Comment by asmirn1** [comment]
@gabijennings Everything looks right to me. Could you send me the raw data file? I'll try to reproduce this error.

**Comment by gabijennings** [comment]
[drive-download-20220929T134043Z-001.zip](https://github.com/ADAP-BIG/adap-big.github.io/files/9755945/drive-download-20220929T134043Z-001.zip)


So sorry for the long delay

**Comment by asmirn1** [comment]
@gabijennings 

Thank you for the files!

I found an issue with reading these mzXML files. I'll create a new version of ADAP-BIG with the fixed issue sometime next week, so you could try it again.

**Comment by asmirn1** [comment]
@gabijennings I've fixed the issue with reading your files in the new version of ADAP-BIG:
https://github.com/ADAP-BIG/adap-big.github.io/releases/tag/v0.2.5

Could you try it and let me know whether it works for you or not.

Also, I've noticed a couple of strange things about the data:
1. Most of MS/MS scans are empty
2. The file says that the data is centroided but the raw data looks like it's in the profile mode. Do you know if it's centroided and profile data?

**Comment by gabijennings** [comment]
Interesting... I was given the data set and told that the data was converted to centroid mode. I'll export the data and centroid it myself and try again.

I downloaded the v.0.2.5 and I am still having the problem of ADAP not opening. It seems like the app crashes before it opens.

**Comment by asmirn1** [comment]
@gabijennings Hm.. Can we have a zoom meeting to see why ADAP is not opening?

Please email me to asmirno1@uncc.edu, and we'll set up a meeting.
